version: "3.1"

services:
  jenkins-jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    # privileged: true
    # user: root
    # ports:
    #   - "8080:8080" # Jenkins web UI
    #   - "50000:50000" # Jenkins agent port
    networks:
      - reverse-proxy
    volumes:
      - "jenkins_home:/var/jenkins_home"

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    driver: bridge

volumes:
  jenkins_home:
