version: "3.1"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    networks:
      - reverse-proxy
    volumes:
      - "jenkins_home:/var/jenkins_home"

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - reverse-proxy

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "8888:9000"
    networks:
      - reverse-proxy
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_conf:/opt/sonarqube/conf

networks:
  reverse-proxy:
    driver: bridge

volumes:
  jenkins_home:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_conf:
