version: "3.1"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    networks:
      - reverse-proxy
    volumes:
      - "jenkins_home:/var/jenkins_home"

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    driver: bridge

volumes:
  jenkins_home:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_conf:
